// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eryttbnfgeacnuhagjrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeXR0Ym5mZ2VhY251aGFnanJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzkyODAsImV4cCI6MjA3MzE1NTI4MH0.-HJPow_707b3kjhyTEXyU7e2V1SujQnG675tJ2ua0GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});